spring.application.name=demo
server.port=9090

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

management.endpoints.web.exposure.include=health,info,metrics

info.app.name=Student Management API
info.app.version=1.0
info.app.description=Spring Boot Student API

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.flyway.enabled=false

spring.data.redis.host=localhost
spring.data.redis.port=6379