spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

management.endpoints.web.exposure.include=health,info,metrics

info.app.name=Student Management API
info.app.version=1.0
info.app.description=Spring Boot Student API